### Criar vídeo
POST https://api-node-js-6382.onrender.com/videos
Content-Type: application/json

{
  "title": "Meu Vídeo",
  "description": "Descrição do vídeo",
  "duration": 120
}

### 
GET https://api-node-js-6382.onrender.com/videos

### 
PUT https://api-node-js-6382.onrender.com/videos/<ID_DO_VIDEO>
Content-Type: application/json

{
  "title": "Vídeo Atualizado",
  "description": "Nova descrição",
  "duration": 200
}

###
DELETE https://api-node-js-6382.onrender.com/videos/<ID_DO_VIDEO>
